services:
#  api:
#    build:
#      context: .
#    container_name: library-api
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db
#    environment:
#      POSTGRES_USER: user
#      POSTGRES_PASSWORD: pass
#      POSTGRES_DB: library
#      DB_HOST: db
#      DB_PORT: 5432
#    volumes:
#      - .:/app

  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data

#volumes:
#  postgres_data: